# Generated by Django 2.0 on 2018-06-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='to_root',
            field=models.BooleanField(default=False),
        ),
    ]
